pipeline {
    agent any

   tools {
        python 'Python3'  // This must match your configured Python tool name
    }

    stages {

        stage('Install dependencies') {
            steps {
                bat 'cd python-calculator-app && python -m pip install --upgrade pip'
                bat 'cd python-calculator-app && python -m pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'cd python-calculator-app && python -m unittest test_operations.py'
            }
        }

        stage('Run Application') {
            steps {
                bat 'cd python-calculator-app && python main.py'
            }
        }
    }
}
