pipeline {
    agent any

        tools {
            'jenkins.plugins.shiningpanda.tools.PythonInstallation' 'Python3'
        }
    
    stages {

        tools {
            python 'Python3'  // <-- your Python tool name here
        }

        stage('Install dependencies') {
            steps {
                bat 'cd python-calculator-app && python -m pip install --upgrade pip'
                bat 'cd python-calculator-app && python -m pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'cd python-calculator-app && python -m unittest test_operations.py'
            }
        }

        stage('Run Application') {
            steps {
                bat 'cd python-calculator-app && python main.py'
            }
        }
    }
}
