---
- name: Install Apache HTTP Server on EC2 instances
  hosts: apacheservers
  become: yes
  gather_facts: no  # disable default fact gathering

  tasks:
    - name: Gather only ansible_distribution fact
      ansible.builtin.setup:
        filter: "ansible_distribution"

    - name: Debug ansible_distribution fact
      debug:
        var: ansible_facts.ansible_distribution

    - name: Install Apache (Amazon Linux)
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts.ansible_distribution == "Amazon"

    - name: Install Apache2 (Ubuntu/Debian)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts.ansible_distribution in ["Ubuntu", "Debian"]

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: "{{ apache_service_name }}"
        state: started
        enabled: yes

  vars:
    apache_service_name: "{{ 'httpd
