pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Install Apache on EC2 instances') {
            steps {
                script {
                    // Call WSL explicitly
                    bat '''
                        wsl ansible-playbook -i /ansible-install-apache/inventory.ini /ansible-install-apache/install_apache.yml
                    '''
                }
            }
        }
    }
}
