pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
        ANSIBLE_SSH_ARGS = '-o StrictModes=no'
    }

    stages {
        stage('Install Apache on EC2 instances') {
            steps {
                script {
                    bat '''
                        wsl bash -c "
                        cp ansible-install-apache/apache-server.pem /tmp/apache-server.pem && \
                        chmod 600 /tmp/apache-server.pem && \
                        ansible-playbook -vvvvv -i ansible-install-apache/inventory.ini ansible-install-apache/install_apache.yml --private-key /tmp/apache-server.pem"
                    '''
                }
            }
        }
    }
}
