pipeline {
    agent any

    tools {
        nodejs 'NodeJS-22'  // Ensure you have configured NodeJS-22 in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/bretondev/Jenkins_Tutorial.git'
            }
        }
        
        stage('Install dependencies') {
            steps {
                dir('node-calculator-app') {
                    bat 'npm install'  // Use bat for Windows to run npm install
                }
            }
        }

        stage('Package') {
            steps {
                dir('node-calculator-app') {
                    bat 'npm test'  // Use bat for Windows to run npm test
                }
            }
        }

        stage('Run Application') {
            steps {
                dir('node-calculator-app') {
                    bat 'npm start'  // Use bat for Windows to run npm start
                }
            }
        }
    }
}
