pipeline {
    agent any

    environment {
        IMAGE_NAME = 'book-crud-app'
        CONTAINER_NAME = 'book-crud-container'
        PORT = '8081'
    }

    stages {

      stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest", "-f Dockerfile .")
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove container if already running
                    sh """
                        if docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}\$"; then
                            docker stop ${CONTAINER_NAME} || true
                            docker rm ${CONTAINER_NAME} || true
                        fi
                    """
                    // Run container
                    sh "docker run -d --name ${CONTAINER_NAME} -p ${PORT}:8081 ${IMAGE_NAME}:latest"
                }
            }
        }
    }

}
