apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-management-webapp
  labels:
    app: book-management-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-management-webapp
  template:
    metadata:
      labels:
        app: book-management-webapp
    spec:
      containers:
      - name: book-management-webapp
        image: 296369311089.dkr.ecr.eu-west-3.amazonaws.com/book-management-webapp:latest
        ports:
        - containerPort: 8080
        # Add env, resources, probes here if needed
---
apiVersion: v1
kind: Service
metadata:
  name: book-management-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: book-management-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
