apiVersion: v1
kind: Service
metadata:
  name: book-management-webapp
spec:
  type: LoadBalancer
  selector:
    app: book-management-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
